language: android
jdk:
- oraclejdk8
branches:
  only:
    - master # only when merging into master will trigger the build
env:
  matrix:
  - ANDROID_TARGET=android-26 ANDROID_ABI=armeabi-v7a android.enableAapt2=false
  global:
  - ADB_INSTALL_TIMEOUT=8
android:
  components:
  - tools                 # add this line if you want to use the lates build tools
  - build-tools-26.0.2    # add this line if you want to use the lates build tools
  - android-26
  - extra-google-google_play_services  # we use google play gcm. so it's required.
  - extra-google-m2repository          # for support library
  - extra-android-m2repository         # for support library
  licenses:
      - 'android-sdk-license-.+'
      - '.*intel.+'
before_install:
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
install:
  # Update sdk tools to latest version and install/update components
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
#script:
#- "./gradlew assembleStagingDebug crashlyticsUploadDistributionStagingDebug"  # assembleStagingDebug is debug build, crashlyticsUploadDistributionStagingDebug is the task to distrubte via Fabric Beta
#- "./gradlew assembleProductionRelease crashlyticsUploadDistributionProductionRelease" # assembleProductionRelease is production build includes signing information in build.gradle. crashlyticsUploadDistributionProductionRelease is the task to distrubte via Fabric Beta
#- "./gradlew emailApk"  # I added a new task in build.gradle. send out the apk via SMTP
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
addons:
  artifacts:
    debug: true
